"""users table

Revision ID: 338f6cfe8dbb
Revises: 
Create Date: 2018-09-02 16:25:10.046280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '338f6cfe8dbb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_equipment_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device', sa.String(length=32), nullable=False),
    sa.Column('activity', sa.String(length=90), nullable=False),
    sa.Column('lend_at', sa.String(length=32), nullable=False),
    sa.Column('lend_user', sa.String(length=32), nullable=False),
    sa.Column('memo_user', sa.String(length=32), nullable=False),
    sa.Column('rememo_user', sa.String(length=32), nullable=True),
    sa.Column('return_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_equipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_name', sa.String(length=32), nullable=False),
    sa.Column('device_type', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_name')
    )
    op.create_table('app_phonebook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('administrative_unit', sa.String(length=32), nullable=False),
    sa.Column('office_location', sa.String(length=32), nullable=False),
    sa.Column('office_person', sa.String(length=32), nullable=True),
    sa.Column('telephone', sa.String(length=11), nullable=False),
    sa.Column('notation', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=32), nullable=False),
    sa.Column('event_place', sa.String(length=90), nullable=False),
    sa.Column('event_date', sa.String(length=32), nullable=False),
    sa.Column('event_status', sa.String(length=2), nullable=True),
    sa.Column('sponsor', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_signin_dutys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sdut_id', sa.String(length=11), nullable=False),
    sa.Column('duty_at', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_signin_dutys_sdut_id'), 'app_signin_dutys', ['sdut_id'], unique=True)
    op.create_table('app_signin_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sdut_id', sa.String(length=11), nullable=False),
    sa.Column('status', sa.String(length=2), nullable=True),
    sa.Column('duration', sa.String(length=9), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_signin_records_sdut_id'), 'app_signin_records', ['sdut_id'], unique=False)
    op.create_table('app_workloads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('department', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=32), nullable=False),
    sa.Column('wk_count', sa.String(length=5), nullable=True),
    sa.Column('manager', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('youth_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('sdut_id', sa.String(length=11), nullable=False),
    sa.Column('department', sa.String(length=32), nullable=False),
    sa.Column('grade', sa.String(length=4), nullable=True),
    sa.Column('phone', sa.String(length=11), nullable=False),
    sa.Column('birthday', sa.String(length=20), nullable=True),
    sa.Column('role_num', sa.String(length=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_youth_users_name'), 'youth_users', ['name'], unique=False)
    op.create_index(op.f('ix_youth_users_sdut_id'), 'youth_users', ['sdut_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_youth_users_sdut_id'), table_name='youth_users')
    op.drop_index(op.f('ix_youth_users_name'), table_name='youth_users')
    op.drop_table('youth_users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('app_workloads')
    op.drop_index(op.f('ix_app_signin_records_sdut_id'), table_name='app_signin_records')
    op.drop_table('app_signin_records')
    op.drop_index(op.f('ix_app_signin_dutys_sdut_id'), table_name='app_signin_dutys')
    op.drop_table('app_signin_dutys')
    op.drop_table('app_schedules')
    op.drop_table('app_phonebook')
    op.drop_table('app_equipments')
    op.drop_table('app_equipment_records')
    # ### end Alembic commands ###
